input_features:
  - name: Pregnancies
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: Glucose
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: BloodPressure
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: SkinThickness
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: Insulin
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: BMI
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: DiabetesPedigreeFunction
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
  - name: Age
    type: number
    preprocessing:
      missing_value_strategy: fill_with_mean
output_features:
  - name: Outcome
    type: category
